// SPDX-License-Identifier: AGPL-3.0-or-later

//! PLUGIN_NAME - A paint.type plugin
//!
//! PLUGIN_DESCRIPTION
//!
//! Generated by plugin-minter

use paint_type_plugins::{
    effect::EffectPlugin,
    manifest::PluginManifest,
    tool::ToolPlugin,
};

/// Plugin implementation
#[cfg(feature = "effect")]
pub struct PLUGIN_CAMEL_NAME;

#[cfg(feature = "effect")]
impl EffectPlugin for PLUGIN_CAMEL_NAME {
    // TODO: Implement effect plugin
}

#[cfg(feature = "tool")]
pub struct PLUGIN_CAMEL_NAME;

#[cfg(feature = "tool")]
impl ToolPlugin for PLUGIN_CAMEL_NAME {
    // TODO: Implement tool plugin
}
